// YouTube region codes for trending videos
export const REGION_CODES = [
  { value: "GLOBAL", label: "Global" },
  { value: "US", label: "United States" },
  { value: "GB", label: "United Kingdom" },
  { value: "IN", label: "India" },
  { value: "JP", label: "Japan" },
  { value: "KR", label: "South Korea" },
  { value: "CA", label: "Canada" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "AU", label: "Australia" },
  { value: "BR", label: "Brazil" },
  { value: "RU", label: "Russia" },
  { value: "MX", label: "Mexico" },
  { value: "ES", label: "Spain" },
  { value: "IT", label: "Italy" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "ZA", label: "South Africa" },
  { value: "TR", label: "Turkey" },
  { value: "ID", label: "Indonesia" },
  { value: "MY", label: "Malaysia" },
  { value: "PH", label: "Philippines" },
  { value: "SG", label: "Singapore" },
  { value: "NL", label: "Netherlands" },
  { value: "PL", label: "Poland" },
  { value: "SE", label: "Sweden" },
  { value: "HK", label: "Hong Kong" },
  { value: "TW", label: "Taiwan" },
  { value: "TH", label: "Thailand" },
  { value: "VN", label: "Vietnam" },
  { value: "EG", label: "Egypt" },
  { value: "AR", label: "Argentina" },
  { value: "CO", label: "Colombia" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "PT", label: "Portugal" },
  { value: "CH", label: "Switzerland" },
  { value: "CL", label: "Chile" },
  { value: "RO", label: "Romania" },
  { value: "BE", label: "Belgium" },
  { value: "GR", label: "Greece" },
  { value: "UA", label: "Ukraine" },
  { value: "CZ", label: "Czech Republic" },
];
